### ISSUE TITLE
Crashing at PolarBleApiDefaultImpl.defaultImplementation(context, PolarBleApi.FEATURE_HR)

### ISSUE THREAD

**Issue by timobaehr** [polarofficial/polar-ble-sdk#81]
Already with the first call my example app crashes at call `PolarBleApiDefaultImpl.defaultImplementation(context, PolarBleApi.FEATURE_HR)`.

Crash log:
```
java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at polar.com.sdk.impl.BDBleApiImpl.<init>(BDBleApiImpl.java:93)
        at polar.com.sdk.api.PolarBleApiDefaultImpl.defaultImplementation(PolarBleApiDefaultImpl.java:19)
        at com.example.MainActivity.onCreate(MainActivity.kt:46)
```

I'm using latest version of Polar BLE SDK (2.2.2).

**Comment by timobaehr** [comment]
OK, documentation is incomplete. These lines are also necessary to get rid of this error:

```gradle
android {
   ...
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```
